[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--clang-tidy",
  "--query-driver=/usr/bin/gcc*,/usr/bin/g++*,/usr/bin/cc,/usr/bin/c++",
  "-j=4",
  "--header-insertion=never",
  "--completion-style=detailed"
]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-language-server"]
auto-format = true

[[language]]
name = "scss"
language-servers = ["vscode-css-language-server", "tailwindcss-language-server"]
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-language-server"]
auto-format = true
