[bar]
order = "default"

[bar.default]
center = ["clock", "media"]
concave_edge_corners = false
end = ["tray", "notifications", "clipboard", "bluetooth", "volume", "brightness", "battery", "session"]
margin_ends = 0
radius = 0
shadow = false
start = ["workspaces"]
thickness = 20

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true
fingerprint = false

[shell.panel]
shadow = false

[theme]
community_palette = "Breeze"
custom_palette = "noctalia-wallpaper-mo"
mode = "dark"
source = "custom"

[theme.templates]
builtin_ids = ["foot", "helix", "niri", "starship", "btop", "qt"]

[wallpaper]
directory = ""
enabled = true
